[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]
cmds = ["echo 'Skipping frontend build - backend only'"]

[start]
cmd = "cd backend && npm start"
